### ISSUE TITLE
Add API functions

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/mobile_detect#2]
To give this module more of a purpose, what about adding some API wrapper functions? Something like:

```php
mobile_detect_load()
mobile_detect_is_mobile()
mobile_detect_is_tablet()
etc.
```

**Comment by laryn** [comment]
I'm open to it, for sure, @BWPanda!

(Mostly I needed this when porting a module and wanted to get something out there that could be used more generally and built upon by anyone else needing this library.)

**Comment by laryn** [comment]
There was an existing D7 module for mobile_detect which I was unaware of when I made this simple wrapper. I've merged it into here with https://github.com/backdrop-contrib/mobile_detect/commit/b4e2fb77b738b3f6af466975995e44a606d665fd

That should provide "more of a purpose" but feel free to test and improve what is there.
