### ISSUE TITLE
When viewing with tablet the `$detect->isMobile()` always returns TRUE

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/mobile_detect#3]
For magic on only mobile phones excluding tablets I had to use:

```
if ($detect->isMobile() == TRUE && $detect->isTablet() == FALSE) {
```

It works just fine for me this way, however so future users of this module can avoid similar confusion, the `$detect->isMobile()` could be improved to return TRUE only on mobile devices and not on tablets.

**Comment by laryn** [comment]
This looks like something the library provides to us:

 - https://github.com/serbanghita/Mobile-Detect/blob/10d919b34a0dbd2a72a3c90b09f797edef66988a/Mobile_Detect.php#L1352-L1359

However, I do see that you might be able to use `if (mobile_detect_check_type('isHandheld')) {` as a slight shortcut:

 - https://github.com/backdrop-contrib/mobile_detect/blob/a3c6bb535e7476583a9dbd5e7c6692b99e6217aa/mobile_detect.module#L64-L81
