### ISSUE TITLE
Update Mobile Detect version

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/mobile_detect#4]
I see that `2.8.37` is available and we have `2.8.34`. Hopefully a simple drop in replacement that should update some user agent strings at least.

**Comment by laryn** [comment]
@alanmels While looking into https://github.com/backdrop-contrib/mobile_detect/issues/3 for you I noticed we're not on the latest release. It looks like it should be a drop in replacement -- are you able to test the latest head?

**Comment by alanmels** [comment]
@laryn, as I said on https://github.com/backdrop-contrib/mobile_detect/issues/3 it works for the purpose of the project I was working on. Unfortunately I have no any extra time, so I had to move on.
